/* One authentication owner. No content is loaded before server-verified identity. */
(()=>{
'use strict';
const cfg=window.TENIS_AI_SUPABASE||{};let client=null,user=null,profile=null,epoch=0,recovery=false;
const msg=t=>{document.querySelector('#auth-message').textContent=t};
function emit(){window.dispatchEvent(new CustomEvent('tenis-auth',{detail:{user,profile,recovery}}))}
function lock(){document.querySelector('#product-shell').hidden=true;document.querySelector('#auth-screen').hidden=false;user=null;profile=null;emit()}
async function sync(){const ticket=++epoch;try{const {data,error}=await client.auth.getUser();if(ticket!==epoch)return;if(error||!data.user){lock();msg('Zaloguj się, aby wejść do aplikacji.');return}const r=await client.from('profiles').select('id,username,role,banned_at').eq('id',data.user.id).single();if(ticket!==epoch)return;if(r.error||!r.data||r.data.banned_at){lock();msg(r.data?.banned_at?'Konto jest zablokowane.':'Nie można odczytać profilu. Spróbuj ponownie.');return}user=data.user;profile=r.data;document.querySelector('#auth-screen').hidden=!recovery;document.querySelector('#product-shell').hidden=recovery;emit();}catch{if(ticket===epoch){lock();msg('Nie można sprawdzić sesji. Sprawdź połączenie i spróbuj ponownie.')}}}
const api={get client(){return client},get user(){return user},get profile(){return profile},get role(){return ['admin','moderator'].includes(profile?.role)?profile.role:'user'},get authenticated(){return !!user&&!!profile&&!recovery},sync,async signOut(){++epoch;lock();const {error}=await client.auth.signOut();if(error)throw error;msg('Wylogowano.')}};window.TenisAccount=api;
document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();if(!client)return;const f=e.currentTarget,button=f.querySelector('button');button.disabled=true;msg('Chwila…');try{const fd=new FormData(f);const r=recovery?await client.auth.updateUser({password:String(fd.get('password'))}):await client.auth.signInWithPassword({email:String(fd.get('email')).trim(),password:String(fd.get('password'))});if(r.error)throw r.error;if(recovery){recovery=false;location.hash='#start';f.querySelector('[name=email]').closest('label').hidden=false;f.querySelector('[name=email]').required=true;button.textContent='Zaloguj się'}f.querySelector('[name=password]').value='';await sync()}catch(e){msg(e.message||'Logowanie nie powiodło się.')}finally{button.disabled=false}};
document.querySelector('#reset-password').onclick=async()=>{if(!client)return;const email=document.querySelector('[name=email]');if(!email.reportValidity())return;try{const {error}=await client.auth.resetPasswordForEmail(email.value.trim(),{redirectTo:cfg.siteUrl||location.origin+location.pathname});if(error)throw error;msg('Jeśli konto istnieje, otrzymasz wiadomość z linkiem do zmiany hasła.')}catch(e){msg(e.message||'Nie udało się wysłać wiadomości.')}};
try{if(!cfg.url||!cfg.publishableKey||!window.supabase?.createClient)throw Error();client=window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});client.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){recovery=true;const f=document.querySelector('#login-form');f.querySelector('[name=email]').required=false;f.querySelector('[name=email]').closest('label').hidden=true;f.querySelector('[name=password]').minLength=8;f.querySelector('button').textContent='Zapisz nowe hasło';msg('Wpisz nowe hasło.')}if(event==='SIGNED_OUT'){++epoch;lock()}else setTimeout(sync,0)});sync()}catch{lock();msg('Logowanie chwilowo niedostępne. Odśwież stronę.');document.querySelector('#login-form button').disabled=true}
})();
