let all=[]; let historyRows=[]; let statsData=null; let filter='all'; let view='matches';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const score=x=>x==null?'':`${Math.round(x)} / 100`;
const pct=x=>x==null?'—':`${Number(x).toFixed(1).replace('.0','')}%`;
function cls(x){return x==null?'':x>=80?'elite':x>=72?'good':x<55?'warn':''}
function pill(label,x,extra=''){if(x==null)return '';return `<div class="market ${cls(x)}"><span>${esc(label)}</span><b>${score(x)}</b>${extra?`<em>${esc(extra)}</em>`:''}</div>`}
function marketBox(title,content,tag='MODEL',extraClass=''){if(!content)return '';return `<details class="marketbox ${extraClass}"><summary><span class="summary-title">${title}</span><span class="tag">${esc(tag)}</span><span class="chev">⌄</span></summary><div class="marketbody">${content}</div></details>`}
function statTable(a,b){return `<table><tr><td></td><td>${esc(a.player)}</td><td>${esc(b.player)}</td></tr><tr><td>Mecze próbki</td><td>${a.matches}</td><td>${b.matches}</td></tr><tr><td>Ta nawierzchnia</td><td>${a.surface_matches??'—'}</td><td>${b.surface_matches??'—'}</td></tr><tr><td>Ranking</td><td>${a.rank??'—'}</td><td>${b.rank??'—'}</td></tr><tr><td>Win rate</td><td>${a.won==null?'—':Math.round(a.won*100)+'%'}</td><td>${b.won==null?'—':Math.round(b.won*100)+'%'}</td></tr><tr><td>Hold</td><td>${a.hold_rate==null?'—':Math.round(a.hold_rate*100)+'%'}</td><td>${b.hold_rate==null?'—':Math.round(b.hold_rate*100)+'%'}</td></tr><tr><td>Return points</td><td>${a.return_points_won==null?'—':Math.round(a.return_points_won*100)+'%'}</td><td>${b.return_points_won==null?'—':Math.round(b.return_points_won*100)+'%'}</td></tr><tr><td>1. set win hist.</td><td>${a.first_set_won==null?'—':Math.round(a.first_set_won*100)+'%'}</td><td>${b.first_set_won==null?'—':Math.round(b.first_set_won*100)+'%'}</td></tr><tr><td>2. set win hist.</td><td>${a.second_set_won==null?'—':Math.round(a.second_set_won*100)+'%'}</td><td>${b.second_set_won==null?'—':Math.round(b.second_set_won*100)+'%'}</td></tr><tr><td>Mecze / 7 dni</td><td>${a.matches_7d??'—'}</td><td>${b.matches_7d??'—'}</td></tr><tr><td>Dni od meczu</td><td>${a.days_since_last??'—'}</td><td>${b.days_since_last??'—'}</td></tr><tr><td>Śr. gemy 1 seta</td><td>${a.first_set_games==null?'—':a.first_set_games.toFixed(1)}</td><td>${b.first_set_games==null?'—':b.first_set_games.toFixed(1)}</td></tr></table>`}
function binary(title,data,tag='MODEL'){if(!data)return '';return marketBox(title,`<div class="twocol">${Object.entries(data).map(([name,v])=>pill(name,v)).join('')}</div>`,tag)}
function gameStates(m){if(!m.game_states)return '';const body=['1','2','4','6'].map(n=>{const states=m.game_states[n];if(!states)return '';return `<div class="checkpoint"><h4>Po ${n} ${n==='1'?'gemie':'gemach'}</h4><div class="pillgrid">${Object.entries(states).map(([s,v])=>pill(s,v)).join('')}</div></div>`}).join('');return marketBox('🎮 Wynik po gemach',body)}
function overUnder(m){if(!m.over_under)return '';const body=Object.entries(m.over_under).map(([line,v])=>`<div class="line"><h4>Linia ${line}</h4><div class="twocol">${pill(`Over ${line}`,v.over)}${pill(`Under ${line}`,v.under)}</div></div>`).join('');return marketBox('📏 Liczba gemów · 1. set',body)}
function matchOverUnder(m){if(!m.match_over_under)return '';const exp=m.expected_match_games==null?'':` · śr. ${m.expected_match_games}`;const body=Object.entries(m.match_over_under).map(([line,v])=>`<div class="line"><h4>Linia ${line}</h4><div class="twocol">${pill(`Over ${line}`,v.over)}${pill(`Under ${line}`,v.under)}</div></div>`).join('');return marketBox('📊 Liczba gemów · cały mecz',body,`MODEL BO3${exp}`)}
function exactSet(m){if(!m.exact_first_set)return '';const entries=Object.entries(m.exact_first_set).filter(([,v])=>v>=1).slice(0,14);return marketBox('🎯 Dokładny wynik 1. seta',`<div class="pillgrid exact">${entries.map(([s,v])=>pill(s,v)).join('')}</div>`)}
function exactMatch(m){if(!m.exact_match_score)return '';return marketBox('🎯 Dokładny wynik meczu',`<div class="pillgrid exact four">${Object.entries(m.exact_match_score).map(([s,v])=>pill(s,v)).join('')}</div>`,'MODEL BO3')}
function statsBox(m){const body=`${statTable(m.p1_stats,m.p2_stats)}${m.service_model?`<p class="modelnote">Model hold: ${esc(m.p1)} ${m.service_model.p1_hold}% · ${esc(m.p2)} ${m.service_model.p2_hold}%</p>`:''}`;return marketBox('📚 Statystyki zawodników',body,'DANE')}
function scheduled(m){if(!m.scheduled_time)return '';const d=new Date(m.scheduled_time);return isNaN(d)?'':d.toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit'})}
function bestSignals(m){const c=[];const addBinary=(prefix,obj)=>{if(!obj)return;const e=Object.entries(obj).sort((a,b)=>b[1]-a[1])[0];if(e)c.push({label:`${prefix}: ${e[0]}`,v:e[1]})};addBinary('Mecz',m.match_win);addBinary('1. set',m.first_set_win);addBinary('2. set',m.second_set_win);addBinary('3. set*',m.third_set_win);addBinary('Sety',m.total_sets);if(m.over_under)Object.entries(m.over_under).forEach(([line,v])=>c.push(v.over>=v.under?{label:`1S O${line}`,v:v.over}:{label:`1S U${line}`,v:v.under}));if(m.match_over_under)Object.entries(m.match_over_under).forEach(([line,v])=>c.push(v.over>=v.under?{label:`M O${line}`,v:v.over}:{label:`M U${line}`,v:v.under}));const top=c.filter(x=>x.v>=68).sort((a,b)=>b.v-a.v).slice(0,3);if(!top.length)return '';return `<div class="signals"><div class="signals-title">🔥 Najmocniejsze sygnały modelu</div><div class="signals-grid">${top.map(x=>pill(x.label,x.v)).join('')}</div></div>`}
function tourKey(m){const t=(m.tour||'').toLowerCase();if(t.includes('chall'))return 'challenger';if(t==='itf'||t.includes('itf'))return 'itf';if(t==='wta')return 'wta';if(t==='atp')return 'atp';return t}
function clientCurrent(m){if(!m.scheduled_time)return true;const t=new Date(m.scheduled_time).getTime();return !Number.isFinite(t)||t>=Date.now()-30*60*1000}
function filteredReady(){return all.filter(m=>m.model_ready&&m.first_set_win&&clientCurrent(m))}
function updateCounts(){const ready=filteredReady();const counts={all:ready.length,atp:0,wta:0,challenger:0,itf:0};ready.forEach(m=>{const k=tourKey(m);if(k in counts&&k!=='all')counts[k]++});document.querySelectorAll('#tour-nav button').forEach(b=>{const n=counts[b.dataset.filter]??0;const c=b.querySelector('.count');if(c)c.textContent=n});const el=document.querySelector('#matched');if(el)el.textContent=`Dopasowane: ${ready.length} / ${all.length}`}
function renderMatches(){const app=document.querySelector('#app');let rows=filteredReady().filter(m=>filter==='all'||tourKey(m)===filter);if(!rows.length){app.innerHTML='<div class="empty"><b>Brak aktualnych meczów z wystarczającymi danymi w tej kategorii.</b><br><br>Stare/rozpoczęte mecze są automatycznie zdejmowane z głównej listy.</div>';return}app.innerHTML=rows.map(m=>`<article class="card"><div class="top"><span>${esc(m.tour||'—')} · ${esc(m.tournament||'—')} · ${esc(m.surface||'?')}</span><span class="quality">DANE ${esc(m.quality)} · MODEL ${Math.round(m.model_confidence||0)}</span></div><div class="matchrow"><div class="match">${esc(m.p1)} <span class="vs">vs</span> ${esc(m.p2)}</div>${scheduled(m)?`<div class="time">${scheduled(m)}</div>`:''}</div>${bestSignals(m)}<div class="markets">${binary('🏆 Zwycięzca meczu',m.match_win,'MODEL BO3')}${binary('🥇 Zwycięzca 1. seta',m.first_set_win)}${binary('🥈 Zwycięzca 2. seta',m.second_set_win)}${binary('🥉 Zwycięzca 3. seta · jeśli będzie',m.third_set_win,'MODEL BO3')}${binary('🔢 Liczba setów w meczu',m.total_sets,'MODEL BO3')}${exactMatch(m)}${gameStates(m)}${overUnder(m)}${matchOverUnder(m)}${exactSet(m)}${statsBox(m)}</div><div class="pick"><b>🎯 Model 1. seta: ${esc(m.pick_first_set)}</b><br><small>${esc(m.note||'')}</small></div></article>`).join('')}
function summaryCard(title,data){const a=data?.accuracy;return `<div class="stat-card"><span>${esc(title)}</span><b>${a==null?'—':pct(a)}</b><small>${data?.hits||0} ✅ · ${data?.misses||0} ❌ · ${data?.settled||0} rozliczonych</small></div>`}
function renderGroup(title,obj){const rows=Object.entries(obj||{}).sort((a,b)=>(b[1].settled||0)-(a[1].settled||0));if(!rows.length)return '';return `<section class="stats-section"><h3>${title}</h3><div class="stats-list">${rows.map(([k,v])=>`<div class="stats-row"><span>${esc(k)}</span><b>${v.accuracy==null?'—':pct(v.accuracy)}</b><small>${v.hits} / ${v.settled}</small></div>`).join('')}</div></section>`}
function renderStats(){const app=document.querySelector('#app');const s=statsData||{};const o=s.overall||{};app.innerHTML=`<section class="stats-hero"><div><span>📊 Skuteczność zielonych</span><b>${o.accuracy==null?'—':pct(o.accuracy)}</b><small>Próg zielonego: ${s.green_threshold??72}/100</small></div><div class="stats-mini"><span>Śledzone mecze <b>${s.matches_tracked||0}</b></span><span>Oczekują <b>${s.matches_pending||0}</b></span><span>Wyłączone z % <b>${s.excluded_signals||0}</b></span></div></section><div class="stat-grid">${summaryCard('Wszystkie rozliczone',o)}</div>${renderGroup('Według rynku',s.by_market)}${renderGroup('Według touru',s.by_tour)}${renderGroup('Według siły sygnału',s.by_score_band)}<p class="stats-note">Do skuteczności liczymy tylko sygnały, które da się jednoznacznie rozliczyć z wyniku końcowego. Typy „wynik po 2/4/6 gemach” są na darmowych danych oznaczane jako nieweryfikowalne i nie psują statystyki.</p>`}
const resultIcon=r=>({hit:'✅',miss:'❌',pending:'⏳',unverifiable:'➖',void:'↩️'}[r]||'⏳');
const resultText=r=>({hit:'WESZŁO',miss:'NIE WESZŁO',pending:'OCZEKUJE',unverifiable:'BRAK GAME-BY-GAME',void:'NIE LICZYMY'}[r]||'OCZEKUJE');
function finalScore(e){const r=e.result;if(!r)return 'Oczekuje na wynik';if(r.status==='void')return 'Mecz nierozliczany';if(r.sets?.length)return r.sets.map(s=>s.join(':')).join(' · ');return r.score_text||'Zakończony'}
function renderHistory(){const app=document.querySelector('#app');const rows=historyRows.filter(e=>{if(!(e.signals||[]).length)return false;if(e.status==='settled'||e.status==='void')return true;const t=new Date(e.scheduled_time||'').getTime();return Number.isFinite(t)&&t<=Date.now()+5*60*1000}).slice(0,150);if(!rows.length){app.innerHTML='<div class="empty"><b>Historia jest jeszcze pusta.</b><br><br>Od teraz zielone sygnały będą zapisywane przed meczem i pojawią się tutaj po starcie spotkania.</div>';return}app.innerHTML=`<div class="history-head"><b>🕘 Historia zielonych sygnałów</b><span>${rows.length} ostatnich meczów</span></div>${rows.map(e=>`<article class="history-card"><div class="top"><span>${esc((e.tour||'').toUpperCase())} · ${esc(e.tournament||'—')}</span><span class="history-status ${e.status}">${e.status==='settled'?'ROZLICZONY':e.status==='void'?'NIE LICZYMY':'OCZEKUJE'}</span></div><div class="history-match">${esc(e.p1)} <span>vs</span> ${esc(e.p2)}</div><div class="history-score">${esc(finalScore(e))}</div><details><summary>Zielone typy (${e.signals.length}) <span class="chev">⌄</span></summary><div class="history-signals">${e.signals.map(s=>`<div class="history-signal ${s.result||'pending'}"><div><b>${resultIcon(s.result)} ${esc(s.label)}</b><span>${esc(s.pick)} · ${score(s.score)}</span></div><strong>${resultText(s.result)}</strong></div>`).join('')}</div></details></article>`).join('')}`}
function render(){document.querySelector('#match-controls').style.display=view==='matches'?'block':'none';document.querySelector('#matched').style.display=view==='matches'?'inline-block':'none';if(view==='matches')renderMatches();else if(view==='stats')renderStats();else renderHistory()}
async function safeJson(url,fallback){try{const r=await fetch(url+'?'+Date.now());if(!r.ok)return fallback;return await r.json()}catch{return fallback}}
async function load(){try{const [results,meta,hist,stat]=await Promise.all([safeJson('data/results.json',[]),safeJson('data/meta.json',{}),safeJson('data/history.json',[]),safeJson('data/history_stats.json',{})]);all=results;historyRows=hist;statsData=stat;document.querySelector('#updated').textContent=meta.updated_at?'Aktualizacja: '+new Date(meta.updated_at).toLocaleString('pl-PL'):'Aktualizacja: —';document.querySelector('#mode').textContent='Źródło: '+(meta.fixtures_mode||'—');updateCounts();render()}catch(e){document.querySelector('#app').innerHTML='<div class="empty">Nie udało się wczytać danych.</div>'}}
document.querySelectorAll('#tour-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tour-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderMatches()});
document.querySelectorAll('.main-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.main-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;render()});
document.querySelector('#refresh').onclick=load;if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');load();setInterval(()=>{if(view==='matches'){updateCounts();renderMatches()}},60000);
