/* Tenis AI — isolated NEURO SHADOW dashboard.
   Read-only UI: never modifies MODEL/RAW, Symphony or PLAYABLE. */
(()=>{
'use strict';
if(window.TENIS_AI_NEURO_SHADOW)return;
const VERSION='v9.3.15';
const PATHS={stats:'data/neuro_shadow_stats_v935.json',training:'data/neuro_shadow_neural_v936.json',current:'data/neuro_shadow_current_v936.json'};
let cache=null,promise=null,navTimer=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=v=>Number.isFinite(Number(v))?`${(Number(v)*100).toFixed(1).replace('.0','')}%`:'—';
const dec=v=>Number.isFinite(Number(v))?Number(v).toFixed(4):'—';
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const fetchJson=async path=>{try{const r=await fetch(`${path}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():null}catch{return null}};
async function load(force=false){if(cache&&!force)return cache;if(promise&&!force)return promise;promise=Promise.all([fetchJson(PATHS.stats),fetchJson(PATHS.training),fetchJson(PATHS.current)]).then(([stats,training,current])=>{cache={stats:stats||{},training:training||{},current:current||{}};promise=null;return cache});return promise}
function metric(label,value,sub=''){return `<div class="neuro936-metric"><span>${esc(label)}</span><b>${esc(value)}</b>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function progress(label,value,max){const n=Math.max(0,num(value)),m=Math.max(1,num(max)),p=Math.min(100,100*n/m);return `<div class="neuro936-progress"><div><span>${esc(label)}</span><b>${n} / ${m}</b></div><i><em style="width:${p.toFixed(1)}%"></em></i></div>`}
function marketRows(training,compatible=true){const rows=Object.entries(training?.markets||{}).map(([market,r])=>({market,...r})).sort((a,b)=>num(b?.gate?.settled)-num(a?.gate?.settled));if(!rows.length)return '<div class="neuro936-empty">Jeszcze nie ma zebranych rynków NEURO.</div>';return `<div class="neuro936-market-list">${rows.map(r=>{const ready=compatible&&r.status==='SHADOW_MODEL_READY',gate=r.gate||{},val=r.validation||{},base=r.state_baseline_validation||{};return `<div class="neuro936-market"><div class="neuro936-market-head"><b>${esc(r.market.replaceAll('_',' '))}</b><span class="${ready?'ready':'collecting'}">${ready?'SHADOW READY':compatible?'ZBIERANIE':'STALE ARTIFACT'}</span></div>${progress('Rozliczone',gate.settled||0,gate.min_settled||80)}<small>hit ${gate.hits||0} · miss ${gate.misses||0}${ready?` · Brier NEURO ${dec(val.brier)} vs state ${dec(base.brier)}`:''}</small></div>`}).join('')}</div>`}
function dashboard(data){const s=data.stats||{},t=data.training||{},c=data.current||{},o=s.overall||{},compatible=c.training_artifact_compatible!==false,ready=compatible&&Array.isArray(t.ready_markets)?t.ready_markets:[];const status=!compatible?'STALE ARTIFACT':ready.length?'SHADOW READY':'COLLECTING DATA';return `<section class="neuro936-shell"><header class="neuro936-hero"><div><span>🧠 NEURO</span><h2>Neural Meta Model</h2><p>Oddzielny SHADOW. Uczy się na rozliczonych prognozach i nie wpływa na PLAYABLE ani Symfonię.</p></div><strong>SHADOW</strong></header><div class="neuro936-grid">${metric('Historia',t.history_rows??s.total_predictions??0,'zapisanych prognoz')}${metric('Rozliczone',s.scored??o.n??0,'hit/miss')}${metric('Rynki gotowe',ready.length,`z ${t.markets_seen||0}`)}${metric('Aktualne selekcje',c.rows_count||0,`${c.neural_rows_count||0} z aktywnym NEURO`)}</div><section class="neuro936-quality"><h3>Jakość SHADOW</h3><div class="neuro936-grid small">${metric('Accuracy',pct(o.accuracy))}${metric('Brier',dec(o.brier))}${metric('Log-loss',dec(o.log_loss))}${metric('Status',status)}</div></section><section class="neuro936-section"><h3>Postęp modeli per rynek</h3>${marketRows(t,compatible)}</section><div class="neuro936-contract">🔒 Brak auto-promocji · brak wpływu PROD · brak kursów bukmachera w cechach · brak wymyślonych prawdopodobieństw.</div></section>`}
function ensureHub(){let hub=document.querySelector('#neuro936-hub');if(hub)return hub;hub=document.createElement('section');hub.id='neuro936-hub';hub.className='neuro936-hub';hub.hidden=true;hub.innerHTML='<div class="neuro936-hub-frame"><header class="neuro936-hub-top"><div><b>🧠 NEURO</b><small>Neural Meta Model · SHADOW</small></div><button type="button" data-neuro-close aria-label="Zamknij">✕</button></header><div class="neuro936-hub-body"></div></div>';document.body.appendChild(hub);hub.querySelector('[data-neuro-close]')?.addEventListener('click',close);return hub}
function markNav(active=true){document.querySelectorAll('#p751-bottom-nav [data-p751-nav]').forEach(btn=>btn.classList.toggle('active',active&&btn.dataset.p751Nav==='neuro'))}
function close(){const hub=document.querySelector('#neuro936-hub');if(hub)hub.hidden=true;document.documentElement.classList.remove('neuro936-hub-open');markNav(false)}
async function open(){const hub=ensureHub(),body=hub.querySelector('.neuro936-hub-body');hub.hidden=false;document.documentElement.classList.add('neuro936-hub-open');markNav(true);body.innerHTML='<div class="neuro936-loading">🧠 Ładowanie NEURO SHADOW…</div>';body.innerHTML=dashboard(await load(true));return true}
function bindNav(){const root=document.querySelector('#p751-bottom-nav');if(!root)return false;let btn=root.querySelector('[data-p751-nav="neuro"]');if(!btn){btn=document.createElement('button');btn.type='button';btn.dataset.p751Nav='neuro';btn.innerHTML='<span>🧠</span><b>NEURO</b>';btn.setAttribute('aria-label','NEURO SHADOW');const sym=root.querySelector('[data-p751-nav="symphony2"]');sym?sym.insertAdjacentElement('afterend',btn):root.appendChild(btn)}btn.onclick=e=>{e.preventDefault();e.stopPropagation();open()};return true}
function scheduleNav(){clearTimeout(navTimer);if(bindNav())return;[50,200,700,1500,3000].forEach(ms=>setTimeout(bindNav,ms))}
function normalizeId(v){try{return decodeURIComponent(String(v??'')).replace(/^id:/,'')}catch{return String(v??'').replace(/^id:/,'')}}
function currentMatch(feed,overlay){const id=normalizeId(overlay?.dataset?.matchKey);return (feed?.matches||[]).find(m=>normalizeId(m.match_id)===id)||null}
function neuroLine(row){const label=[row.player,row.pick,row.line].filter(v=>v!==null&&v!==undefined&&v!=='').join(' · ')||row.market;const neural=row.neural_probability==null?(row.neural_status==='STALE_MODEL_ARTIFACT'?'NEURO: stale artifact':'NEURO: zbieranie'):`NEURO ${pct(row.neural_probability)}`;return `<div class="neuro936-detail-line"><span>${esc(label)}</span><small>${esc(String(row.market||'').replaceAll('_',' '))}</small><b>STATE ${pct(row.state_probability)}<em>${neural}</em></b></div>`}
async function toggleMatchPanel(button){const panel=button.closest('.sbmc922-panel'),overlay=button.closest('#p751-match-overlay');if(!panel||!overlay)return;let box=panel.querySelector('.neuro936-match-panel');if(box){box.remove();button.classList.remove('active');return}button.classList.add('active');const data=await load(),match=currentMatch(data.current,overlay);box=document.createElement('div');box.className='neuro936-match-panel';box.innerHTML=match&&match.rows?.length?`<div class="neuro936-match-title"><b>🧠 NEURO SHADOW</b><span>${match.rows.length} selekcji</span></div>${match.rows.map(neuroLine).join('')}`:'<div class="neuro936-empty">NEURO: brak aktualnie przechwyconych selekcji dla tego meczu.</div>';panel.querySelector('.sbmc922-head')?.after(box)}
function injectBrain(){document.querySelectorAll('.sbmc922-panel .sbmc922-head').forEach(head=>{if(head.querySelector('.neuro936-brain'))return;const b=document.createElement('button');b.type='button';b.className='neuro936-brain';b.title='NEURO SHADOW';b.setAttribute('aria-label','Pokaż NEURO SHADOW');b.textContent='🧠';b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();toggleMatchPanel(b)});head.appendChild(b)})}
function boot(){scheduleNav();const observer=new MutationObserver(()=>{scheduleNav();injectBrain()});observer.observe(document.documentElement,{subtree:true,childList:true});injectBrain()}
window.TENIS_AI_NEURO_SHADOW=Object.freeze({version:VERSION,load,open,close,dashboard,injectBrain,bindNav});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();