import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const c={window:{}};vm.createContext(c);
for(const p of ['presentation-data.js','match-detail-data.js'])vm.runInContext(fs.readFileSync('frontend/'+p,'utf8'),c);
const d=c.window.TenisMatchDetail;
const presentation=c.window.TenisPresentation;
const fixture={p1:'Łukasz Żuk',p2:'João Silva',p1_id:10,p2_id:20,scheduled_time:'2099-01-01'};
assert.equal(presentation.key({id:'match-1',match_id:'match-1'}),'match-1','Consistent canonical IDs stay routable');
assert.equal(presentation.key({match_id:'match-1'}),'match-1','A single canonical match_id stays routable');
assert.equal(presentation.key({p1:'A',p2:'B',scheduled_time:'2099-01-01'}),null,'Route identity must not fall back to player names and time');
assert.equal(presentation.key({id:'match-1',match_id:'other'}),null,'Conflicting canonical IDs must fail closed');
assert.deepEqual(Array.from(presentation.routableRows([{id:'ok'},{p1:'A',p2:'B',scheduled_time:'2099-01-01'},{id:'x',match_id:'y'}]),x=>x.id),['ok'],'Only rows with exactly one canonical identity may enter current routes');
const past={p1:'SILVA, JOAO',p2:'Zuk, Lukasz',scheduled_time:'2020-01-01',result:{winner:'Łukasz Żuk',score_text:'4-6 4-6'}};
const exactPast={...past,p1_id:20,p2_id:10};
assert.equal(d.historyRows([past],fixture,'p1',true).length,0,'Name-only history must stay unassociated / N/D');
assert.equal(d.historyRows([exactPast],fixture,'p1',true).length,1,'Canonical player IDs may associate H2H even with reversed sides');
assert.equal(d.winnerSide(past),'p2');
assert.equal(d.historyRows([{...past,p1_id:99,p2_id:10}],fixture,'p1',true).length,0,'Partial/conflicting IDs must not fall back to names');
assert.equal(d.historyRows([{...exactPast,p1:'Alias B',p2:'Alias A'}],fixture,'p1',true).length,1,'Canonical IDs, not player-name spelling, own the association');
assert.equal(d.historyRows([{...exactPast,scheduled_time:'2100-01-01'}],fixture,'p1',true).length,0);
assert.equal(d.historyRows([exactPast,exactPast],fixture,'p1',true).length,1);
assert.equal(d.historyRows([{...exactPast,result:null}],fixture,'p1',true).length,0);
assert.equal(d.assessment({...fixture,match_win:{'Łukasz Żuk':60}}).p,null,'Never generate missing complement');
assert.equal(d.assessment({...fixture,match_win:{'Łukasz Żuk':60,'João Silva':40}}).winner,'p1');
assert.equal(d.comparison({...fixture,p1_rank:150,p2_rank:100})[0].winner,'p2');
assert.equal(d.comparison({...fixture,p1_rank:null,p2_rank:100})[0].winner,null);
assert.equal(d.sampleLabel(null),'N/D - brak danych o liczbie meczów w próbce','Missing sample count must stay N/D');
assert.equal(d.sampleLabel(undefined),'N/D - brak danych o liczbie meczów w próbce','Undefined sample count must stay N/D');
assert.equal(d.sampleLabel(0),'0 meczów w próbce','Explicit backend zero must remain a real zero');
assert.equal(d.sampleLabel(12),'12 meczów w próbce','Published sample count must be preserved');
const appSource=fs.readFileSync('frontend/app.js','utf8');
assert(appSource.includes('MD.sampleLabel(s.matches)'),'Player profile must render the canonical sample label');
assert(!appSource.includes('s.matches??0'),'Missing sample count must not be coerced to zero in the profile');
assert(appSource.includes('state.matches=D.routableRows(index.matches)'),'Current delivery index must reject unroutable identities before route state');
assert(appSource.includes('state.symphony={...x,matches:D.routableRows(x.matches)}'),'Current Symphony route data must reject unroutable identities');
assert(!appSource.includes('date(new Date().toISOString())'),'Page header must not present the client clock as data publication time');
assert(appSource.includes('date(state.meta.updated_at)'),'Page header publication time must come from backend delivery generated_at');
for(const [values,trend] of [[[.3,.5,.6],'rosnący'],[[.6,.5,.3],'spadkowy'],[[.5,.5,.5],'stabilny'],[[.3,.6,.5],'zmienny'],[[null,.5,.6],'N/D']]){
 const m={player_intelligence_v85:{profiles:{p1:{windows:Object.fromEntries([20,10,5].map((n,i)=>[n,{metrics:{won:{adjusted:values[i]}}}]))}}}};
 assert.equal(d.form(m,'p1').trend,trend);
}
const fixtures=JSON.parse(fs.readFileSync('frontend/data/results.json')),history=JSON.parse(fs.readFileSync('frontend/data/history.json'));
const detailHistory=JSON.parse(fs.readFileSync('frontend/data/match_detail_history.json'))?.matches||[];
let found=0,safeArchive=0;for(const m of fixtures){const rows=d.historyRows(history,m,'p1',true);found+=rows.length;assert(rows.every(r=>Date.parse(r.scheduled_time)<Date.parse(m.scheduled_time)));const archiveRows=d.historyRows(detailHistory,m,'p1',true);safeArchive+=archiveRows.length;assert(archiveRows.every(r=>r.p1_id!=null&&r.p2_id!=null),'Published H2H association must carry canonical player IDs')}
assert.equal(found,0,'Name-only settled history must not fabricate current-player H2H');
console.log('PASS Stage 2: identity, missing values, published probabilities, trends; name-only H2H:',found,'canonical archive H2H:',safeArchive);
