-- iNeed$ V1: durable SHADOW bankroll/value/risk ledger. Applied to production 2026-09-10.
create table if not exists public.ineed_experiments (
  id uuid primary key default gen_random_uuid(),
  experiment_no bigint generated by default as identity unique,
  name text not null, operator text not null, mode text not null, currency text not null default 'PLN',
  starting_bankroll numeric(14,4) not null, config jsonb not null, config_version text not null,
  status text not null default 'ACTIVE', started_at timestamptz not null default now(), ended_at timestamptz,
  final_bankroll numeric(14,4), created_by uuid, created_at timestamptz not null default now()
);
create unique index if not exists ineed_one_active_experiment on public.ineed_experiments((status)) where status='ACTIVE';

create table if not exists public.ineed_signals (
  id uuid primary key default gen_random_uuid(), experiment_id uuid not null references public.ineed_experiments(id) on delete cascade,
  fingerprint text not null, status text not null, reason_code text, match_id text not null, market text not null, selection text,
  odds numeric, odds_timestamp timestamptz, model_probability numeric, raw_implied_probability numeric, no_vig_probability numeric,
  break_even_probability numeric, fair_odds numeric, edge_probability_points numeric, expected_value_net numeric,
  estimated_bookmaker_margin numeric, confidence numeric, data_quality text, proposed_stake numeric, final_stake numeric,
  current_snapshot jsonb not null default '{}'::jsonb, first_seen_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(experiment_id,fingerprint)
);
create table if not exists public.ineed_decision_snapshots (
  id uuid primary key default gen_random_uuid(), experiment_id uuid not null references public.ineed_experiments(id) on delete cascade,
  signal_id uuid not null references public.ineed_signals(id) on delete cascade, snapshot_hash text not null, evaluated_at timestamptz not null,
  odds numeric, odds_timestamp timestamptz, status text not null, reason_code text, snapshot jsonb not null, created_at timestamptz not null default now(),
  unique(signal_id,snapshot_hash)
);
create table if not exists public.ineed_signal_events (
  id uuid primary key default gen_random_uuid(), experiment_id uuid not null references public.ineed_experiments(id) on delete cascade,
  signal_id uuid not null references public.ineed_signals(id) on delete cascade, from_status text, to_status text not null, reason_code text,
  event_at timestamptz not null default now()
);
create table if not exists public.ineed_shadow_bets (
  id uuid primary key default gen_random_uuid(), experiment_id uuid not null references public.ineed_experiments(id) on delete cascade,
  signal_id uuid not null unique references public.ineed_signals(id) on delete cascade, match_id text not null, market text not null, selection text,
  status text not null default 'PENDING', stake numeric(14,4) not null, odds numeric not null, potential_payout numeric, payout numeric,
  net_profit numeric, bankroll_before numeric not null, bankroll_after numeric, placement_snapshot jsonb not null,
  settlement_snapshot jsonb, placed_at timestamptz not null default now(), settled_at timestamptz
);
create table if not exists public.ineed_bankroll_ledger (
  id uuid primary key default gen_random_uuid(), experiment_id uuid not null references public.ineed_experiments(id) on delete cascade,
  entry_type text not null, amount numeric(14,4) not null, source text not null, source_key text not null, bet_id uuid references public.ineed_shadow_bets(id),
  bankroll_before numeric(14,4) not null, bankroll_after numeric(14,4) not null, created_at timestamptz not null default now(),
  unique(experiment_id,source_key)
);
create table if not exists public.ineed_email_events (
  id uuid primary key default gen_random_uuid(), experiment_id uuid not null references public.ineed_experiments(id) on delete cascade,
  signal_id uuid not null references public.ineed_signals(id) on delete cascade, event_type text not null, revision integer not null default 1,
  status text not null default 'PENDING', payload jsonb not null, provider_message_id text, attempt_count integer not null default 0,
  last_error text, created_at timestamptz not null default now(), sent_at timestamptz,
  unique(signal_id,event_type,revision)
);
create table if not exists public.ineed_runtime_health (
  experiment_id uuid primary key references public.ineed_experiments(id) on delete cascade, status text not null default 'NEVER_RUN',
  last_sync_at timestamptz, detail jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now()
);

create or replace function public.ineed_log_signal_status() returns trigger language plpgsql security definer set search_path='public' as $$
begin
  if tg_op='INSERT' or new.status is distinct from old.status or new.reason_code is distinct from old.reason_code then
    insert into public.ineed_signal_events(experiment_id,signal_id,from_status,to_status,reason_code)
    values(new.experiment_id,new.id,case when tg_op='INSERT' then null else old.status end,new.status,new.reason_code);
  end if;
  return new;
end $$;
drop trigger if exists ineed_signal_status_audit on public.ineed_signals;
create trigger ineed_signal_status_audit after insert or update of status,reason_code on public.ineed_signals for each row execute function public.ineed_log_signal_status();

alter table public.ineed_experiments enable row level security;
alter table public.ineed_signals enable row level security;
alter table public.ineed_decision_snapshots enable row level security;
alter table public.ineed_signal_events enable row level security;
alter table public.ineed_shadow_bets enable row level security;
alter table public.ineed_bankroll_ledger enable row level security;
alter table public.ineed_email_events enable row level security;
alter table public.ineed_runtime_health enable row level security;

do $$ declare t text; begin
  foreach t in array array['ineed_experiments','ineed_signals','ineed_decision_snapshots','ineed_signal_events','ineed_shadow_bets','ineed_bankroll_ledger','ineed_email_events','ineed_runtime_health'] loop
    execute format('drop policy if exists ineed_staff_read on public.%I',t);
    execute format('create policy ineed_staff_read on public.%I for select to authenticated using (public.is_staff(auth.uid()))',t);
    execute format('revoke insert,update,delete on public.%I from anon, authenticated',t);
    execute format('grant select on public.%I to authenticated',t);
  end loop;
end $$;

create or replace function public.ineed_admin_start_experiment(next_name text default null, config_override jsonb default null)
returns uuid language plpgsql security definer set search_path='public','auth' as $$
declare uid uuid:=auth.uid(); previous public.ineed_experiments%rowtype; cfg jsonb; start_amount numeric(14,4); cfg_version text; new_id uuid; available numeric(14,4); exposure numeric(14,4);
begin
  if uid is null or not public.is_admin(uid) then raise exception 'Tylko administrator może rozpocząć eksperyment iNeed$.'; end if;
  select * into previous from public.ineed_experiments where status='ACTIVE' for update;
  if found then
    select coalesce((select bankroll_after from public.ineed_bankroll_ledger where experiment_id=previous.id order by created_at desc,id desc limit 1),0) into available;
    select coalesce(sum(stake),0) into exposure from public.ineed_shadow_bets where experiment_id=previous.id and status in ('SHADOW_PLACED','PENDING');
    if exposure>0 then raise exception 'Nie można rozpocząć nowego eksperymentu, gdy poprzedni ma otwarte zakłady.'; end if;
    update public.ineed_experiments set status='COMPLETED',ended_at=now(),final_bankroll=available where id=previous.id;
    cfg:=coalesce(config_override,previous.config);
  else cfg:=config_override; end if;
  if cfg is null then raise exception 'Brak konfiguracji iNeed$.'; end if;
  if coalesce(cfg->>'operator','')<>'superbet.pl' or coalesce(cfg->>'mode','')<>'SHADOW' then raise exception 'V1 obsługuje wyłącznie superbet.pl / SHADOW'; end if;
  start_amount:=(cfg->>'starting_bankroll')::numeric; cfg_version:=coalesce(cfg->>'version','ineed-v1');
  insert into public.ineed_experiments(name,operator,mode,currency,starting_bankroll,config,config_version,status,created_by)
  values(coalesce(nullif(trim(next_name),''),'ROAD TO 1,000,000 — TEST #'||(coalesce((select max(experiment_no) from public.ineed_experiments),0)+1)::text),'superbet.pl','SHADOW','PLN',start_amount,cfg,cfg_version,'ACTIVE',uid) returning id into new_id;
  insert into public.ineed_bankroll_ledger(experiment_id,entry_type,amount,source,source_key,bankroll_before,bankroll_after) values(new_id,'INITIAL_DEPOSIT',start_amount,'experiment_start','initial:'||new_id,0,start_amount);
  insert into public.ineed_runtime_health(experiment_id,status,detail) values(new_id,'NEVER_RUN','{}');
  return new_id;
end $$;

grant execute on function public.ineed_admin_start_experiment(text,jsonb) to authenticated;

create or replace function public.ineed_system_settle_bet(target_bet_id uuid, settlement_outcome text, settlement_payout numeric, settlement_detail jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path='public','auth' as $$
declare b public.ineed_shadow_bets%rowtype; available numeric(14,4); other_exposure numeric(14,4); credit numeric(14,4); after_available numeric(14,4); after_equity numeric(14,4); entry text;
begin
  settlement_outcome:=upper(trim(settlement_outcome)); if settlement_outcome not in ('WIN','LOSS','VOID','CANCELLED') then raise exception 'Invalid iNeed settlement outcome'; end if;
  select * into b from public.ineed_shadow_bets where id=target_bet_id for update; if not found then raise exception 'iNeed bet not found'; end if;
  if b.status in ('WIN','LOSS','VOID','CANCELLED','SETTLED') then return jsonb_build_object('status','IDEMPOTENT','bet_id',b.id,'outcome',b.status); end if;
  select coalesce((select bankroll_after from public.ineed_bankroll_ledger where experiment_id=b.experiment_id order by created_at desc,id desc limit 1),0) into available;
  credit:=case when settlement_outcome='WIN' then greatest(coalesce(settlement_payout,0),0) when settlement_outcome in ('VOID','CANCELLED') then b.stake else 0 end;
  entry:=case settlement_outcome when 'WIN' then 'BET_WIN' when 'LOSS' then 'BET_LOSS' when 'VOID' then 'BET_VOID' else 'BET_CANCELLED' end; after_available:=available+credit;
  insert into public.ineed_bankroll_ledger(experiment_id,entry_type,amount,source,source_key,bet_id,bankroll_before,bankroll_after)
  values(b.experiment_id,entry,credit,'ineed_settlement','settle:'||b.id,b.id,available,after_available) on conflict(experiment_id,source_key) do nothing;
  select coalesce(sum(stake),0) into other_exposure from public.ineed_shadow_bets where experiment_id=b.experiment_id and id<>b.id and status in ('SHADOW_PLACED','PENDING'); after_equity:=after_available+other_exposure;
  update public.ineed_shadow_bets set status=settlement_outcome,payout=credit,net_profit=credit-b.stake,bankroll_after=after_equity,settlement_snapshot=settlement_detail,settled_at=now() where id=b.id;
  update public.ineed_signals set status=settlement_outcome,updated_at=now() where id=b.signal_id;
  return jsonb_build_object('status','SETTLED','bet_id',b.id,'outcome',settlement_outcome,'bankroll_after',after_equity);
end $$;
revoke all on function public.ineed_system_settle_bet(uuid,text,numeric,jsonb) from public,anon,authenticated;
grant execute on function public.ineed_system_settle_bet(uuid,text,numeric,jsonb) to service_role;

insert into public.ineed_experiments(name,operator,mode,currency,starting_bankroll,config,config_version,status)
select 'ROAD TO 1,000,000 — TEST #1','superbet.pl','SHADOW','PLN',200,
'{"version":"ineed-superbet-pl-2026-09-11-v1","operator":"superbet.pl","mode":"SHADOW","currency":"PLN","starting_bankroll":200,"minimum_stake":2,"stake_rounding":0.01,"stake_tax_rate":0.12,"high_win_tax_rate":0.1,"high_win_tax_threshold_pln":2280,"high_win_tax_trigger":"above","fractional_kelly":0.25,"max_single_bet_pct":0.03,"max_match_exposure_pct":0.03,"max_total_exposure_pct":0.15,"minimum_net_ev":0.05,"minimum_edge_pp":4,"minimum_confidence":null,"minimum_odds":1.01,"maximum_odds":null,"odds_max_age_minutes":108,"drawdown":{"caution":0.1,"defensive":0.2,"halted":0.3},"risk_profiles":{"NORMAL":{"stake_multiplier":1,"exposure_multiplier":1,"minimum_net_ev":0.05,"minimum_edge_pp":4},"CAUTION":{"stake_multiplier":0.67,"exposure_multiplier":0.67,"minimum_net_ev":0.07,"minimum_edge_pp":5},"DEFENSIVE":{"stake_multiplier":0.33,"exposure_multiplier":0.33,"minimum_net_ev":0.1,"minimum_edge_pp":6},"HALTED":{"stake_multiplier":0,"exposure_multiplier":0,"minimum_net_ev":1,"minimum_edge_pp":100}},"automatic_real_betting":false,"automatic_recommendations":true,"automatic_settlement":true,"email_alerts":true}'::jsonb,
'ineed-superbet-pl-2026-09-11-v1','ACTIVE'
where not exists(select 1 from public.ineed_experiments);
insert into public.ineed_bankroll_ledger(experiment_id,entry_type,amount,source,source_key,bankroll_before,bankroll_after)
select id,'INITIAL_DEPOSIT',starting_bankroll,'experiment_start','initial:'||id,0,starting_bankroll from public.ineed_experiments e
where e.status='ACTIVE' and not exists(select 1 from public.ineed_bankroll_ledger l where l.experiment_id=e.id);
insert into public.ineed_runtime_health(experiment_id,status,detail)
select id,'NEVER_RUN','{}' from public.ineed_experiments e where e.status='ACTIVE' on conflict(experiment_id) do nothing;
